# Generated by Django 5.0.6 on 2024-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_customuser_delete_cryptocurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
