# Generated by Django 5.0.6 on 2024-07-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='ccrypto_symbol',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
    ]
