# Generated by Django 5.0.6 on 2024-07-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_portfolio_ccrypto_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='ccrypto_symbol',
            new_name='crypto_symbol',
        ),
    ]
